version: '3.8'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/rs-initiate.js
    command: ["--replSet", "rs0"]


volumes:
  mongodb_data_container: